### ISSUE TITLE
Bug report: It error on access

### ISSUE THREAD

**Issue by mikage-961pro** [project-alisa/Ouranos#2]
**Describe the bug**
We were unable to review your app as it error on access. We have attached detailed crash logs to help troubleshoot this issue.

Link Error
[https://millionlive.miyacorata.net/images/piyo.png](https://millionlive.miyacorata.net/images/piyo.png) is 404 - Not Found

 Error
 We were unable to review your app as it error on access.
Error Messages: Mastodonからお知らせを取得できませんでした

**Next Steps**
To resolve this issue, please revise your app and test it on a device to ensure it will launch without erroring.

**Comment by miyacorata** [comment]
Thank you for your bug report. 😄 
But, this error is **not** occur on Ouranos. Your said error is occured on another system Canvas-ML.
That system is not open-source project, but I already recognize of that error. I preparering to fix that errors, so please wait a moment.

**Comment by miyacorata** [comment]
Issue you reported was fixed. Thank you for your bug reporting.
